# ==========================================
# INSTALL DEPENDENCIES
# ==========================================
# !pip install ultralytics -q

import os
import torch
from ultralytics import YOLO
from pathlib import Path

# ==========================================
# CONFIGURATION
# ==========================================
DATASET_YAML   = 'yolo_dataset/dataset.yaml'   # generated by prepare_yolo_dataset.py
RUN_NAME       = 'yolo11_raster_seg'            # name for this training run
PROJECT_DIR    = 'runs'                          # where results are saved

# Training hyperparameters
EPOCHS         = 100
IMAGE_SIZE     = 1024      # must match the patch size used during dataset prep
BATCH_SIZE     = 4         # reduce to 2 if OOM on T4; increase to 8 on A100
PATIENCE       = 20        # early stopping — stops if no improvement for N epochs
LEARNING_RATE  = 0.01
WARMUP_EPOCHS  = 5

# Augmentation — keep moderate since patches are already georeferenced crops
MOSAIC         = 0.5       # blend 4 images (helps with small objects)
FLIPUD         = 0.5       # vertical flip (valid for aerial/satellite imagery)
FLIPLR         = 0.5       # horizontal flip
DEGREES        = 15.0      # rotation up to ±15° (objects can appear at any angle)
TRANSLATE      = 0.1
SCALE          = 0.5


def check_environment():
    print("=" * 50)
    print("Environment Check")
    print("=" * 50)

    if torch.cuda.is_available():
        gpu = torch.cuda.get_device_name(0)
        vram = torch.cuda.get_device_properties(0).total_memory / 1e9
        print(f"  GPU   : {gpu}")
        print(f"  VRAM  : {vram:.1f} GB")

        if vram < 10:
            print("  [!] T4 detected — using batch_size=2 to be safe.")
            return 2   # override batch size for T4
        elif vram >= 30:
            print("  A100 detected — batch_size=8 recommended.")
            return 8
        else:
            return BATCH_SIZE
    else:
        print("  [!] No GPU found. Training on CPU will be very slow.")
        return 2


def verify_dataset(yaml_path):
    print("\nVerifying dataset...")
    import yaml
    with open(yaml_path, 'r') as f:
        cfg = yaml.safe_load(f)

    base = Path(cfg['path'])
    train_imgs = list((base / cfg['train']).glob('*.png'))
    val_imgs   = list((base / cfg['val']).glob('*.png'))

    print(f"  Train images : {len(train_imgs)}")
    print(f"  Val images   : {len(val_imgs)}")
    print(f"  Classes      : {cfg['nc']} → {cfg['names']}")

    if len(train_imgs) == 0:
        raise RuntimeError("No training images found. Run prepare_yolo_dataset.py first.")
    if len(val_imgs) == 0:
        raise RuntimeError("No validation images found.")

    # Spot-check a label file exists for first image
    first_label = (base / cfg['train'].replace('images', 'labels') /
                   (train_imgs[0].stem + '.txt'))
    if not first_label.exists():
        raise RuntimeError(f"Label file missing for {train_imgs[0].name}")

    print("  Dataset OK.")


def main():
    # ------------------------------------------------------------------
    # 1. Environment + dataset checks
    # ------------------------------------------------------------------
    batch = check_environment()
    verify_dataset(DATASET_YAML)

    # ------------------------------------------------------------------
    # 2. Load YOLO11 Large pretrained weights
    # ------------------------------------------------------------------
    print("\nLoading YOLO11 Large model...")
    # Downloads yolo11l.pt automatically on first run (~50 MB)
    model = YOLO('yolo11l.pt')
    print(f"  Parameters : {sum(p.numel() for p in model.model.parameters()) / 1e6:.1f}M")

    # ------------------------------------------------------------------
    # 3. Train
    # ------------------------------------------------------------------
    print(f"\nStarting training — {EPOCHS} epochs, imgsz={IMAGE_SIZE}, batch={batch}")
    print("=" * 50)

    results = model.train(
        data        = DATASET_YAML,
        epochs      = EPOCHS,
        imgsz       = IMAGE_SIZE,
        batch       = batch,
        name        = RUN_NAME,
        project     = PROJECT_DIR,
        patience    = PATIENCE,
        lr0         = LEARNING_RATE,
        warmup_epochs = WARMUP_EPOCHS,

        # Augmentation
        mosaic      = MOSAIC,
        flipud      = FLIPUD,
        fliplr      = FLIPLR,
        degrees     = DEGREES,
        translate   = TRANSLATE,
        scale       = SCALE,

        # Optimization
        optimizer   = 'AdamW',
        cos_lr      = True,       # cosine LR schedule
        amp         = True,       # automatic mixed precision — cuts VRAM ~40%
        cache       = False,      # set True if dataset fits in RAM for faster epochs

        # Logging
        plots       = True,       # save training curve plots
        save        = True,
        save_period = 10,         # save checkpoint every 10 epochs
        exist_ok    = True,
    )

    # ------------------------------------------------------------------
    # 4. Validate best checkpoint
    # ------------------------------------------------------------------
    print("\nValidating best checkpoint...")
    best_weights = Path(PROJECT_DIR) / RUN_NAME / 'weights' / 'best.pt'
    model_best   = YOLO(str(best_weights))
    metrics      = model_best.val(data=DATASET_YAML, imgsz=IMAGE_SIZE)

    print("\n" + "=" * 50)
    print("Results")
    print("=" * 50)
    print(f"  mAP50      : {metrics.box.map50:.4f}")
    print(f"  mAP50-95   : {metrics.box.map:.4f}")
    print(f"  Precision  : {metrics.box.mp:.4f}")
    print(f"  Recall     : {metrics.box.mr:.4f}")

    # ------------------------------------------------------------------
    # 5. Export to ONNX for portability (optional)
    # ------------------------------------------------------------------
    print("\nExporting best model to ONNX...")
    model_best.export(format='onnx', imgsz=IMAGE_SIZE, simplify=True)

    print(f"\nDone!")
    print(f"  Best weights : {best_weights}")
    print(f"  ONNX model   : {best_weights.with_suffix('.onnx')}")
    print(f"  Run folder   : {Path(PROJECT_DIR) / RUN_NAME}/")


if __name__ == "__main__":
    main()
